export AMAZONSPICEOX_GUI_PROFILE=1
export BROWSER=/usr/local/bin/chrome
export ASOX_GUI_BACKEND="${ASOX_GUI_BACKEND:-host-x11}"
export DISPLAY="${DISPLAY:-10.0.2.2:0}"
export LIBGL_ALWAYS_SOFTWARE=1
export NO_AT_BRIDGE=1
