set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -g history-limit 50000
set -g mouse on
set -g status on
set -g status-position bottom
set -g status-style bg=colour235,fg=colour250
set -g status-left '#[fg=colour220,bold] arrakis #[fg=colour208]spice #[fg=colour244]| '
set -g status-right '#[fg=colour244]%Y-%m-%d %H:%M '
setw -g window-status-format '#[fg=colour244] #I:#W '
setw -g window-status-current-format '#[fg=colour232,bg=colour220,bold] #I:#W '
setw -g mode-keys vi
