set -g history-limit 50000
set -g mouse on
set -g status on
set -g status-style bg=colour235,fg=colour250
set -g status-left '#[fg=colour220]arrakis #[fg=colour244]| '
set -g status-right '#[fg=colour244]%Y-%m-%d %H:%M'
setw -g mode-keys vi
