[boot]
systemd=false

[automount]
enabled=true
root=/mnt/
options=metadata,umask=22,fmask=11
mountFsTab=false

[interop]
enabled=true
appendWindowsPath=false

[network]
hostname=arrakis
generateHosts=true
generateResolvConf=false

[user]
default=root
